services:
  - type: web
    name: singularity-oneproject
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node start.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.14.0
